require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

abstract_target 'mDoc' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  
  target 'mDocClinic' do
      #Production-specific pods

      target 'mDocClinicTests' do
        inherit! :complete
        # Pods for testing
      end
    end
  
  target 'mDocClinicDevelopment' do
      #Development-specific pods
  end

  target 'mDocClinicProduction' do
    #Production-specific pods
  end

  

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
